
export const dataProducts = [
    {
      id: "k2P9s1Xe",
      title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
      price: 600,
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    },
    {
      id: "V7n3H5cK",
      title: "Mens Casual Premium Slim Fit T-Shirts ",
      price: 2000,
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    },
    {
      id: "Z9xL6bV1",
      title: "Mens Cotton Jacket",
      price: 5000,
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    },
    {
      id: "mR8j4TqQ",
      title: "Mens Casual Slim Fit",
      price: 7000,
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    },
    {
      id: "bD1e5M7w",
      title: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
      price: 33000,
      category: "jewelery",
      image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      id: "sN4W8cYz",
      title: "Solid Gold Petite Micropave ",
      price: 45000,
      category: "jewelery",
      image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      id: "T3h8P1kJ",
      title: "White Gold Plated Princess",
      price: 55000,
      category: "jewelery",
      image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      id: "qW6d9EzA",
      title: "Pierced Owl Rose Gold Plated Stainless Steel Double",
      price: 51000,
      category: "jewelery",
      image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      id: "xR7K0bMd",
      title: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
      price: 8000,
      category: "electronics",
      image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    },
    {
      id: "Yt2Jv4Lz",
      title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
      price: 1999,
      category: "electronics",
      image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    },
    {
      id: "gW3PzN2r",
      title: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
      price: 9999,
      category: "electronics",
      image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    },
    {
      id: "uC5Vx7Ba",
      title: "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
      price: 11999,
      category: "electronics",
      image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    },
    {
      id: "AZ4jNw6V",
      title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
      price: 29000,
      category: "electronics",
      image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    },
    {
      id: "Rp9Yk7MX",
      title: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor – Super Ultrawide Screen QLED",
      price: 59000,
      category: "electronics",
      image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    },
    {
      id: "Wf8Kd2Lx",
      title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
      price: 1500,
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    },
    {
      id: "tLm6Q9yJ",
      title: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
      price: 3999,
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    },
    {
      id: "jK1Rw7Xz",
      title: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
      price: 799,
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    },
    {
      id: "vPe2Md8L",
      title: "MBJ Women's Solid Short Sleeve Boat Neck V ",
      price: 1199,
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    },
    {
      id: "NfX7uZ3b",
      title: "Opna Women's Short Sleeve Moisture",
      price: 1399,
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    },
    {
      id: "Mtz4Lp6R",
      title: "DANVOUY Womens T Shirt Casual Cotton Short",
      price: 999,
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    },
  ];
  